- hosts: all
  become: true
  vars:
    users:
    - ansible
  
  tasks:
  - name: create the ansible user
    user:
      name: "{{ item }}"
      groups: "wheel"
    with_items: "{{ users }}"
  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
    with_items: "{{ users }}"
  - name: "Allow the ansible user to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers"
      state: "present"
      insertafter: '^root'
      line: "ansible ALL=(ALL) NOPASSWD: ALL"
